// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: server/protos/user/user.proto

package user

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NameUsernameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *NameUsernameReq) Reset() {
	*x = NameUsernameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_protos_user_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameUsernameReq) ProtoMessage() {}

func (x *NameUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_protos_user_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameUsernameReq.ProtoReflect.Descriptor instead.
func (*NameUsernameReq) Descriptor() ([]byte, []int) {
	return file_server_protos_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *NameUsernameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NameUsernameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type NameUsernameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSent bool `protobuf:"varint,1,opt,name=isSent,proto3" json:"isSent,omitempty"`
}

func (x *NameUsernameRes) Reset() {
	*x = NameUsernameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_protos_user_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameUsernameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameUsernameRes) ProtoMessage() {}

func (x *NameUsernameRes) ProtoReflect() protoreflect.Message {
	mi := &file_server_protos_user_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameUsernameRes.ProtoReflect.Descriptor instead.
func (*NameUsernameRes) Descriptor() ([]byte, []int) {
	return file_server_protos_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *NameUsernameRes) GetIsSent() bool {
	if x != nil {
		return x.IsSent
	}
	return false
}

var File_server_protos_user_user_proto protoreflect.FileDescriptor

var file_server_protos_user_user_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x0f, 0x4e, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x4e, 0x61, 0x6d, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x73, 0x53, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53,
	0x65, 0x6e, 0x74, 0x32, 0x4d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x4e, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x76, 0x61, 0x69, 0x62, 0x68, 0x61, 0x76, 0x2f, 0x74, 0x72, 0x79, 0x2d, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_server_protos_user_user_proto_rawDescOnce sync.Once
	file_server_protos_user_user_proto_rawDescData = file_server_protos_user_user_proto_rawDesc
)

func file_server_protos_user_user_proto_rawDescGZIP() []byte {
	file_server_protos_user_user_proto_rawDescOnce.Do(func() {
		file_server_protos_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_protos_user_user_proto_rawDescData)
	})
	return file_server_protos_user_user_proto_rawDescData
}

var file_server_protos_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_protos_user_user_proto_goTypes = []interface{}{
	(*NameUsernameReq)(nil), // 0: user.NameUsernameReq
	(*NameUsernameRes)(nil), // 1: user.NameUsernameRes
}
var file_server_protos_user_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.NameUsername:input_type -> user.NameUsernameReq
	1, // 1: user.UserService.NameUsername:output_type -> user.NameUsernameRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_protos_user_user_proto_init() }
func file_server_protos_user_user_proto_init() {
	if File_server_protos_user_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_protos_user_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameUsernameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_protos_user_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameUsernameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_protos_user_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_protos_user_user_proto_goTypes,
		DependencyIndexes: file_server_protos_user_user_proto_depIdxs,
		MessageInfos:      file_server_protos_user_user_proto_msgTypes,
	}.Build()
	File_server_protos_user_user_proto = out.File
	file_server_protos_user_user_proto_rawDesc = nil
	file_server_protos_user_user_proto_goTypes = nil
	file_server_protos_user_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	NameUsername(ctx context.Context, in *NameUsernameReq, opts ...grpc.CallOption) (*NameUsernameRes, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) NameUsername(ctx context.Context, in *NameUsernameReq, opts ...grpc.CallOption) (*NameUsernameRes, error) {
	out := new(NameUsernameRes)
	err := c.cc.Invoke(ctx, "/user.UserService/NameUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	NameUsername(context.Context, *NameUsernameReq) (*NameUsernameRes, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) NameUsername(context.Context, *NameUsernameReq) (*NameUsernameRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NameUsername not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_NameUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).NameUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/NameUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).NameUsername(ctx, req.(*NameUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NameUsername",
			Handler:    _UserService_NameUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/protos/user/user.proto",
}
